[package]
name = "acars_vdlm2_parser"
version = "0.2.0"
edition = "2021"
authors = ["Alex Austin"]
description = "Library for decoding and encoding ACARS and VDLM2 messages"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
log = "0.4.17"

[dev-dependencies]
rand = "0.8.5"
glob = "0.3.0"
chrono = "0.4.22"
humantime = "2.1.0"
prettytable-rs = "0.9.0"
rayon = "1.5.3"
thousands = "0.2.0"
byte-unit = "4.0.14"
